name: video_trans_high_res
num_gpu: 1

model_type: VideoTransformerModel
pretrained_sampler: ./pretrained_models/video_trans_high_res.pth
dist: False

# network configs
# image autoencoder
img_embed_dim: 256

# sampler configs
dim: 128
depth: 6
dim_head: 64
heads: 12
ff_mult: 4
norm_out: true
attn_dropout: 0.0
ff_dropout: 0.0
final_proj: true
normformer: true
rotary_emb: true
latent_shape: [8, 4]

num_inside_timesteps: 24
