name: sampler_high_res

model_type: AppTransformerModel
pretrained_sampler: ./pretrained_models/sampler_high_res.pth

# network configs
# image autoencoder
img_z_channels: 256

# sampler configs
codebook_size: 1024
bert_n_emb: 512
bert_n_layers: 24
bert_n_head: 8
block_size: 512 # 32 x 16
latent_shape: [32, 16]
embd_pdrop: 0.0
resid_pdrop: 0.0
attn_pdrop: 0.0

sample_steps: 64
