name: sampler_high_res

# pretrained models
img_ae_path: ./pretrained_models/vqgan_decomposed_high_res.pth

model_type: AppTransformerModel
pretrained_sampler: ./pretrained_models/sampler_high_res.pth

# network configs
# image autoencoder
img_embed_dim: 256
img_n_embed: 1024
img_double_z: false
img_z_channels: 256
img_resolution: 512
img_in_channels: 3
img_out_ch: 3
img_ch: 128
img_ch_mult: [1, 1, 2, 2, 4]
img_other_ch_mult: [4, 4]
img_num_res_blocks: 2
img_attn_resolutions: [32]
img_dropout: 0.0

# sampler configs
codebook_size: 1024
bert_n_emb: 512
bert_n_layers: 24
bert_n_head: 8
block_size: 512 # 32 x 16
latent_shape: [32, 16]
embd_pdrop: 0.0
resid_pdrop: 0.0
attn_pdrop: 0.0

sample_steps: 64
